name: Build app and deploy to aliyun
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: centos
    steps:
    - uses: actions/checkout@v1
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        
    - name: Install npm dependencies
      run: npm install
      
    - name: Run build task
      run: npm run build
      
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: dist # 这是要复制到阿里云静态服务器的文件夹名称
          REMOTE_HOST: '47.99.150.145' # 你的阿里云公网地址
          REMOTE_USER: root # 阿里云登录后默认为 root 用户，并且所在文件夹为 root
          TARGET: /home/test # 打包后的 dist 文件夹将放在 /home/test
